language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.1

    # The SDK version used to compile your project
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x64-android-28
    #- sys-img-armeabi-v7a-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  # Prepare pre-accepted licenses to not be prompted at installation
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - ./gradlew build check
